# Generated by Django 4.0.6 on 2023-01-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_database_options_alter_database_r'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
